# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3412cbfedf91db0ed9674c185d925af6e484d1cbef1287996b172d403ac89f5da00c650291671d8a1edfd0a3fe18520e199c14d8c4ea9ef0d8aa9564317f627

test:
  secret_key_base: 998fb6bbd46db3800af1fe1b1542539ee8db91411a9683794c9a88f683c96464d805ec1f0b063658c27dd2f32e09882fa791007ee275b65e9b77f5d0413acdb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
